### ISSUE TITLE
Привести Android Manifest в соответствие с реальностью

### ISSUE THREAD

**Issue by MihaxXx** [megavvve/StudyReady#3]
- Необходимо отразить в качестве минимальной версии ту, начиная с которой вы поддерживаете работу приложения. В Readme указана 7, а приложение установится и на 5, вот только будет ли работать?
- В списке поддерживаемых локалей указаны, кажется, все существующие, хотя поддержки языков отличных от русского, насколько я понимаю, нет
<details>

![image](https://github.com/megavvve/StudyReady/assets/5885676/38604149-9f8e-411b-b48f-a81d099b86a2)
</details>

**Comment by dakuznet** [comment]
Исправлено:
1. Минимальная версия Android.
2. Список поддерживаемых локалей.
![image](https://github.com/megavvve/StudyReady/assets/129334003/ad21004e-99bc-4028-9c26-4baa2de56887)

**Comment by MihaxXx** [comment]
Желательно ещё указывать каким коммитом/PR закрывается ишью.
