### ISSUE TITLE
Ошибки активного диалогового окна не должны затемняться

### ISSUE THREAD

**Issue by MihaxXx** [megavvve/StudyReady#6]
К слову, не уверен, что отсутствие описания - ошибка
<details>
<summary>скрин</summary>

![image](https://github.com/megavvve/StudyReady/assets/5885676/5eb7ad4e-10ba-4b9c-bea0-70b2fd4e0714)
</details>

**Comment by dakuznet** [comment]
Исправлено:
1. Отсутствие описания теперь не является ошибкой.
2. Ошибка активного диалогового окна не затемняется.
![3](https://github.com/megavvve/StudyReady/assets/129334003/004e48e8-cfcb-440f-b55c-80b698c09033)
![2](https://github.com/megavvve/StudyReady/assets/129334003/347f587b-d155-43a0-bff8-672a9e2fd176)
![1png](https://github.com/megavvve/StudyReady/assets/129334003/2eacd9b8-3025-40b2-835b-df2974ecfe01)

**Comment by MihaxXx** [comment]
Выглядит странно, что у поля "Название предмета" ошибка "такой тренажёр уже есть". Если вы выводите ошибки для каждого поля, то они должны быть специфичны для него и касаться его. Может быть и общая валидация формы, но тогда вывод ошибок должен быть в одном место, например, где-то в начале или конце формы.

Кроме того, желательно ещё указывать каким коммитом/PR закрывается ишью.
