### ISSUE TITLE
Сделать UX более интуитивным

### ISSUE THREAD

**Issue by MihaxXx** [megavvve/StudyReady#7]
Во-первых, отказаться от дублирование а рамках одного экрана, в частности - информация о предмете на экране добавления вопроса в тренажёр.
Во-вторых, редактирование тренажёра путём добавления вопросов по одному кажется не слишком удобной, часто нужно добавить несколько сразу, особенно при создании.

**Comment by dakuznet** [comment]
Исправлено:
1. Добавлены подсказки по интерфейсу при первом входе в приложение (на главном экране, на экране тренажеров, на экране материалов.)
![e1f77568-94e8-44db-bb3b-c254e29d5e2e](https://github.com/megavvve/StudyReady/assets/129334003/756e088a-6ca3-4a91-87fc-4c6e408302f3)
![58ebb95d-0b56-459c-a703-6a9023959a0f](https://github.com/megavvve/StudyReady/assets/129334003/c1747d72-f64d-4efb-bf89-fa175664b901)

**Comment by MihaxXx** [comment]
Проблему не решили

**Comment by megavvve** [comment]
> Проблему не решили

Я считаю что частично мы проблему решили и хотел бы прокомментировать изменения.

Во первых, мы добавили подсказки как раз таки для того чтобы User Experience был намного удобнее, понятнее и интуитивнее.
Во-вторых, информация в вопросах по типу предмета у нас дублируется не случайно. Могут быть такие названия предметов, которые идут как например какие нибудь кастомные или смешанные (банальный пример: пользователь решил назвать предмет тренажера "Смешанный", где вопросы находятся из разных названий предметов). 
Тоесть у нас вопрос и тренажер могут иметь разные названия предметов и это нормально)

По поводу добавления вопросов соглашусь, но тогда наверное было бы правильнее это делать как отдельный ишьюс, а не объединять все в один. Уровень проектной деятельности, как я считаю, не подразумевает за собой закрытие огромных ишьюсов(так как добавление нескольких вопросов за раз - это тяжелая фича, для которой нужно придумать сперва удобный дизайн, благодаря которому пользователь сможет спокойно добавлять вопросы, а потом ее реализовать)

**Comment by MihaxXx** [comment]
> мы добавили подсказки как раз таки для того чтобы User Experience был намного удобнее, понятнее и интуитивнее

Подсказки безусловно хороший ход. Кажется, это даже первый раз (или один из) на ПД, когда есть обучение не в игре. Тут молодцы.

> пользователь решил назвать предмет тренажера "Смешанный", где вопросы находятся из разных названий предметов

Не стоит стоить архитектуру из соображений о том, как её будут абьюзить



> соглашусь, но тогда наверное было бы правильнее это делать как отдельный ишьюс, а не объединять все в один.

Если вам для работы нужны были ишью поменьше, вы могли разделить мой на два самостоятельно. Это крайне неубедительное оправдание

**Comment by megavvve** [comment]
Честно говоря здесь я соглашусь, возможно стоило бы разделить два ишью на поменьше, но о такой функции гитхаба мы не знали. 

По поводу фразы "не стоит строить архитектуру из соображений о том, как её будут абьюзить" - не совсем понял. Мы больше все таки делали упор на удобство и было бы неплохо, чтобы например в фильтре по предметам, если пользователь называет его например: "смешанный", то по этому предмету ему выдавались бы тренажеры.
Возможно стоило бы назвать поля ввода "предмет для тренажера" и "предмет для вопроса", но мы решили что для пользователя данное разграничение было очевидным.

**Comment by MihaxXx** [comment]
> о такой функции гитхаба мы не знали

Напрямую такой функции нет, но всегда можно создать ещё один issue, а в исходном зачеркнуть вынесенное и добавить об этом приписку.

> По поводу фразы "не стоит строить архитектуру из соображений о том, как её будут абьюзить" - не совсем понял.

Смотрите, есть 95% пользователей, который использую только стандартный функционал и 5%, которые "наворачивают" на него какие-то свои абстракции в голове. Заботу о последних всегда очень приятно видеть со стороны разработчиков, но она никогда не должна оказываться важнее, чем интересы первых (кроме пары крайностей, но не об этом сейчас).

> Возможно стоило бы назвать поля ввода "предмет для тренажера" и "предмет для вопроса", но мы решили что для пользователя данное разграничение было очевидным.

Так вот для большинства людей два очень похожих поля - это только повод запутаться, т.к. им просто не придёт мысль о том, чтобы смешивать одно с другим, чтобы потом он решили вот так разделять то, что смешали.

> смешивать одно с другим, чтобы потом он решили вот так разделять то, что смешали.

Вот тут уже чувствуете подвох? Разделять то, что ранее осознанно смешали - получается кривой паттерн

> не стоит строить архитектуру из соображений о том, как её будут абьюзить

Ну и возвращаясь к исходному вопросу: Без опыта практически невозможно спроектировать сложную архитектуру дружелюбную к кастомизации, а в рамках прототипирования, которым вполне можно назвать ПД, и не нужно. "Лучше меньше, да лучше" как раз про эту ситуацию - лучше сделать простую и не такую гибкую архитектуру, но такую, чья реализация не будет вводить большинство пользователей в прострацию.
